// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../model/Tyre.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 8475592078562126401),
      name: 'Tyre',
      lastPropertyId: const IdUid(6, 456125844155052306),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1632797661024380226),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5740538060141877190),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1399751980936939927),
            name: 'psi',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8276396776084304369),
            name: 'temp',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 1244599015436944574),
            name: 'isLowPressure',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 456125844155052306),
            name: 'date',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 8475592078562126401),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Tyre: EntityDefinition<Tyre>(
        model: _entities[0],
        toOneRelations: (Tyre object) => [],
        toManyRelations: (Tyre object) => {},
        getId: (Tyre object) => object.id,
        setId: (Tyre object, int id) {
          object.id = id;
        },
        objectToFB: (Tyre object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addFloat64(2, object.psi);
          fbb.addInt64(3, object.temp);
          fbb.addBool(4, object.isLowPressure);
          fbb.addInt64(5, object.date?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final psiParam =
              const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final tempParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final isLowPressureParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 12);
          final object = Tyre(
              name: nameParam,
              psi: psiParam,
              temp: tempParam,
              isLowPressure: isLowPressureParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..date = dateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(dateValue);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Tyre] entity fields to define ObjectBox queries.
class Tyre_ {
  /// see [Tyre.id]
  static final id = QueryIntegerProperty<Tyre>(_entities[0].properties[0]);

  /// see [Tyre.name]
  static final name = QueryStringProperty<Tyre>(_entities[0].properties[1]);

  /// see [Tyre.psi]
  static final psi = QueryDoubleProperty<Tyre>(_entities[0].properties[2]);

  /// see [Tyre.temp]
  static final temp = QueryIntegerProperty<Tyre>(_entities[0].properties[3]);

  /// see [Tyre.isLowPressure]
  static final isLowPressure =
      QueryBooleanProperty<Tyre>(_entities[0].properties[4]);

  /// see [Tyre.date]
  static final date = QueryIntegerProperty<Tyre>(_entities[0].properties[5]);
}
